name: NuGet
on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  nuget:
    name: NuGet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
          source-url: https://nuget.pkg.github.com/pythonology/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}   
      - name: Pack
        run: |
          dotnet pack -c Release --output nupkgs BeatTogether.Core.Data/BeatTogether.Core.Data.csproj
          dotnet pack -c Release --output nupkgs BeatTogether.Core.Hosting/BeatTogether.Core.Hosting.csproj
          dotnet pack -c Release --output nupkgs BeatTogether.Core.Messaging/BeatTogether.Core.Messaging.csproj
          dotnet pack -c Release --output nupkgs BeatTogether.Core.Security/BeatTogether.Core.Security.csproj
      - name: Publish
        run: |
          dotnet nuget push nupkgs/BeatTogether.Core.Data.*.nupkg
          dotnet nuget push nupkgs/BeatTogether.Core.Hosting.*.nupkg
          dotnet nuget push nupkgs/BeatTogether.Core.Messaging.*.nupkg
          dotnet nuget push nupkgs/BeatTogether.Core.Security.*.nupkg
